import type { Vehicle } from "@/types";

/**
 * Demo inventory – development only.
 * These are clearly marked as DEMO DATA and should be removed
 * or replaced with real Supabase records in production.
 */
export const DEMO_VEHICLES: Vehicle[] = [
  {
    id: "demo-1",
    slug: "2022-maruti-suzuki-swift-vxi",
    brand: "Maruti Suzuki",
    model: "Swift",
    variant: "VXI",
    year: 2022,
    registration_year: 2022,
    fuel_type: "Petrol",
    transmission: "Manual",
    body_type: "Hatchback",
    kilometres: 18500,
    owners: 1,
    price: 620000,
    engine: "1197 cc",
    mileage: "23.2 kmpl",
    power: "89 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Excellent",
    description: "Well-maintained first-owner Swift in excellent condition. All services done at authorised service centre.",
    is_featured: true,
    is_published: true,
    status: "available",
    color: "Pearl Midnight Black",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80",
    images: [{ id: "di-1", vehicle_id: "demo-1", url: "https://images.unsplash.com/photo-1609521263047-f8f205293f24?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-2",
    slug: "2021-hyundai-creta-sx-diesel",
    brand: "Hyundai",
    model: "Creta",
    variant: "SX Diesel",
    year: 2021,
    registration_year: 2021,
    fuel_type: "Diesel",
    transmission: "Manual",
    body_type: "SUV",
    kilometres: 32000,
    owners: 1,
    price: 1250000,
    engine: "1493 cc",
    mileage: "21.4 kmpl",
    power: "113 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Excellent",
    description: "Premium Creta SX with sunroof, ventilated seats, and all features. Single owner, company-maintained.",
    is_featured: true,
    is_published: true,
    status: "available",
    color: "Typhoon Silver",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    images: [{ id: "di-2", vehicle_id: "demo-2", url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-3",
    slug: "2020-honda-city-vx-cvt",
    brand: "Honda",
    model: "City",
    variant: "VX CVT",
    year: 2020,
    registration_year: 2020,
    fuel_type: "Petrol",
    transmission: "CVT",
    body_type: "Sedan",
    kilometres: 41000,
    owners: 1,
    price: 980000,
    engine: "1497 cc",
    mileage: "17.8 kmpl",
    power: "118 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Good",
    description: "Elegant Honda City with automatic transmission. Clean, well-maintained. Perfect city and highway car.",
    is_featured: true,
    is_published: true,
    status: "available",
    color: "Radiant Red",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80",
    images: [{ id: "di-3", vehicle_id: "demo-3", url: "https://images.unsplash.com/photo-1542362567-b07e54358753?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-4",
    slug: "2019-toyota-innova-crysta-gx",
    brand: "Toyota",
    model: "Innova Crysta",
    variant: "GX",
    year: 2019,
    registration_year: 2019,
    fuel_type: "Diesel",
    transmission: "Manual",
    body_type: "MUV",
    kilometres: 67000,
    owners: 1,
    price: 1450000,
    engine: "2393 cc",
    mileage: "15.1 kmpl",
    power: "148 bhp",
    seating: 7,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Good",
    description: "Iconic Toyota Innova Crysta with full service history. 7-seater, perfect for families.",
    is_featured: true,
    is_published: true,
    status: "available",
    color: "Super White",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80",
    images: [{ id: "di-4", vehicle_id: "demo-4", url: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-5",
    slug: "2023-tata-nexon-xz-plus",
    brand: "Tata",
    model: "Nexon",
    variant: "XZ+ Petrol",
    year: 2023,
    registration_year: 2023,
    fuel_type: "Petrol",
    transmission: "Manual",
    body_type: "SUV",
    kilometres: 8200,
    owners: 1,
    price: 1080000,
    engine: "1199 cc",
    mileage: "17 kmpl",
    power: "118 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Excellent",
    description: "Nearly new Tata Nexon XZ+ with panoramic sunroof, JBL sound system, and all ADAS features.",
    is_featured: true,
    is_published: true,
    status: "available",
    color: "Calgary White",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80",
    images: [{ id: "di-5", vehicle_id: "demo-5", url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-6",
    slug: "2021-kia-seltos-htx-plus",
    brand: "Kia",
    model: "Seltos",
    variant: "HTX+ Petrol",
    year: 2021,
    registration_year: 2021,
    fuel_type: "Petrol",
    transmission: "CVT",
    body_type: "SUV",
    kilometres: 28500,
    owners: 1,
    price: 1320000,
    engine: "1497 cc",
    mileage: "16.5 kmpl",
    power: "113 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Excellent",
    description: "Premium Kia Seltos with panoramic sunroof, Bose sound system, and ADAS. Always garaged.",
    is_featured: false,
    is_published: true,
    status: "available",
    color: "Gravity Grey",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80",
    images: [{ id: "di-6", vehicle_id: "demo-6", url: "https://images.unsplash.com/photo-1619682817481-e994891cd1f5?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-7",
    slug: "2018-volkswagen-polo-gt-tsi",
    brand: "Volkswagen",
    model: "Polo",
    variant: "GT TSI",
    year: 2018,
    registration_year: 2018,
    fuel_type: "Petrol",
    transmission: "Automatic",
    body_type: "Hatchback",
    kilometres: 54000,
    owners: 1,
    price: 740000,
    engine: "999 cc",
    mileage: "16.2 kmpl",
    power: "108 bhp",
    seating: 5,
    insurance: "Third Party",
    service_history: true,
    condition: "Good",
    description: "Fun-to-drive Polo GT TSI with DSG gearbox. Enthusiast's choice, well maintained.",
    is_featured: false,
    is_published: true,
    status: "available",
    color: "Flash Red",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80",
    images: [{ id: "di-7", vehicle_id: "demo-7", url: "https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-8",
    slug: "2020-maruti-suzuki-baleno-alpha",
    brand: "Maruti Suzuki",
    model: "Baleno",
    variant: "Alpha",
    year: 2020,
    registration_year: 2020,
    fuel_type: "Petrol",
    transmission: "Manual",
    body_type: "Hatchback",
    kilometres: 38000,
    owners: 1,
    price: 680000,
    engine: "1197 cc",
    mileage: "21.4 kmpl",
    power: "82 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Good",
    description: "Top variant Baleno Alpha with all features including Apple CarPlay, heads-up display.",
    is_featured: false,
    is_published: true,
    status: "available",
    color: "Nexa Blue",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80",
    images: [{ id: "di-8", vehicle_id: "demo-8", url: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-9",
    slug: "2022-mahindra-thar-lx-4wd",
    brand: "Mahindra",
    model: "Thar",
    variant: "LX 4WD",
    year: 2022,
    registration_year: 2022,
    fuel_type: "Diesel",
    transmission: "Manual",
    body_type: "SUV",
    kilometres: 22000,
    owners: 1,
    price: 1580000,
    engine: "2184 cc",
    mileage: "15.2 kmpl",
    power: "130 bhp",
    seating: 4,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Excellent",
    description: "Iconic Mahindra Thar in top LX variant. Perfect for off-road adventures, low km.",
    is_featured: true,
    is_published: true,
    status: "available",
    color: "Aquamarine",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80",
    images: [{ id: "di-9", vehicle_id: "demo-9", url: "https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-10",
    slug: "2021-ford-ecosport-titanium",
    brand: "Ford",
    model: "EcoSport",
    variant: "Titanium+",
    year: 2021,
    registration_year: 2021,
    fuel_type: "Petrol",
    transmission: "Automatic",
    body_type: "SUV",
    kilometres: 30000,
    owners: 1,
    price: 920000,
    engine: "1499 cc",
    mileage: "15.9 kmpl",
    power: "122 bhp",
    seating: 5,
    insurance: "Comprehensive",
    service_history: true,
    condition: "Good",
    description: "Well-maintained EcoSport Titanium+ with automatic gearbox, SYNC3 infotainment.",
    is_featured: false,
    is_published: true,
    status: "reserved",
    color: "Moondust Silver",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80",
    images: [{ id: "di-10", vehicle_id: "demo-10", url: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-11",
    slug: "2020-renault-kwid-climber",
    brand: "Renault",
    model: "Kwid",
    variant: "Climber",
    year: 2020,
    registration_year: 2020,
    fuel_type: "Petrol",
    transmission: "Manual",
    body_type: "Hatchback",
    kilometres: 45000,
    owners: 2,
    price: 380000,
    engine: "999 cc",
    mileage: "22.5 kmpl",
    power: "67 bhp",
    seating: 5,
    insurance: "Third Party",
    service_history: false,
    condition: "Fair",
    description: "Budget-friendly Kwid Climber edition. Good condition, ideal for city driving.",
    is_featured: false,
    is_published: true,
    status: "available",
    color: "Moonlight Silver",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1493238792000-8113da705763?w=800&q=80",
    images: [{ id: "di-11", vehicle_id: "demo-11", url: "https://images.unsplash.com/photo-1493238792000-8113da705763?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
  {
    id: "demo-12",
    slug: "2019-honda-amaze-vx-cvt",
    brand: "Honda",
    model: "Amaze",
    variant: "VX CVT",
    year: 2019,
    registration_year: 2019,
    fuel_type: "Petrol",
    transmission: "CVT",
    body_type: "Sedan",
    kilometres: 58000,
    owners: 1,
    price: 720000,
    engine: "1198 cc",
    mileage: "18.6 kmpl",
    power: "88 bhp",
    seating: 5,
    insurance: "Third Party",
    service_history: true,
    condition: "Good",
    description: "Reliable Honda Amaze with CVT automatic gearbox. All services done at Honda ASC.",
    is_featured: false,
    is_published: true,
    status: "available",
    color: "Lunar Silver",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    cover_image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80",
    images: [{ id: "di-12", vehicle_id: "demo-12", url: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?w=800&q=80", is_cover: true, sort_order: 0, created_at: "" }],
  },
];

export const DEMO_BRANDS = [
  "Maruti Suzuki", "Hyundai", "Honda", "Toyota", "Tata",
  "Kia", "Volkswagen", "Mahindra", "Ford", "Renault",
  "MG", "Skoda", "Jeep", "Nissan", "Datsun",
];

export const DEMO_FAQS = [
  {
    id: "faq-1",
    question: "How do I buy a car from JP CARS?",
    answer: "Browse our inventory online or visit us in Kallakurichi. Select a car you like, book a test drive, and our team will assist you with the complete buying process including finance and documentation.",
    category: "Buying",
    sort_order: 1,
    is_published: true,
  },
  {
    id: "faq-2",
    question: "Do you offer finance or EMI options?",
    answer: "Yes, we assist with vehicle financing through leading banks and NBFCs. Our team will help you understand eligibility and get the best interest rates. Approval is subject to bank criteria.",
    category: "Finance",
    sort_order: 2,
    is_published: true,
  },
  {
    id: "faq-3",
    question: "Can I sell my car to JP CARS?",
    answer: "Absolutely. Submit your car details through our 'Sell Your Car' page and our team will evaluate it and get back to you with a fair offer.",
    category: "Selling",
    sort_order: 3,
    is_published: true,
  },
  {
    id: "faq-4",
    question: "Are the vehicles inspected before listing?",
    answer: "Yes, every vehicle listed on JP CARS goes through a thorough inspection covering mechanical condition, exterior, interior, and documentation verification.",
    category: "Quality",
    sort_order: 4,
    is_published: true,
  },
  {
    id: "faq-5",
    question: "Do you help with RC transfer?",
    answer: "Yes, we assist with RC transfer documentation as part of our vehicle purchase service. Our team guides you through every step.",
    category: "Documentation",
    sort_order: 5,
    is_published: true,
  },
  {
    id: "faq-6",
    question: "Can I get a test drive before buying?",
    answer: "Yes. Book a test drive through our website or WhatsApp us directly. We'll arrange a test drive at our location in Kallakurichi.",
    category: "Buying",
    sort_order: 6,
    is_published: true,
  },
];
